name: Build

on:
  pull_request:
    branches:
      - main
      - compose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build project and run local and device tests
        run: ./gradlew :app:assembleDebug
        
